name:  ${project.artifactId}
main: com.crazycraft.dev.CrazyCraft.CrazyCraft
version:  ${project.version}
author: [intronate67]
commands:
    gm:
        description: Gamemode command.
    afk:
        description: Afk Command
    bal:
        description: Check your balance.
    balance:
        description: Check your balance.
    clear:
        description: Clear your inventory.
    fly:
        description: Fly Away my child.
    freeze:
        description: Freeze a player.
    give:
        description: Give an item.
    god:
        description: Be invincible.
    home:
        description: Go home.
    kit:
        description: Get a kit.
    me:
        description: Say what you're doing.
    msg:
        description: Message other players
    whisper:
        description: Whisper to another player.
    tell:
        description: Tell another player something.
    pm:
        description: Private message a pleyer.
    mute:
        description: Mute that hoe.
    playertime:
        description: Set time for you.
    r:
        description: Respond to another player.
    seen:
        description: Se info about offline/online players.
    slap:
        description: Slap that hoe.
    slay:
        description: Kill that mean person.
    spawnmob:
        description: Spawn a mob where you are looking.
    speed:
        description: Change your walking/flying speed
    time:
        description: Set the time for your world.
    tppos:
        description: Teleport to a specific location.
    unafk:
        description: Welcome back.
    unfreeze:
        description: YOU ARE ALIVE.
    ungod:
        description: You are normal again.
    who:
        description: Whos online.
    list:
        description: List who is online.
    tp:
        description: Teleport to people.
    tpa:
        description: Request to teleport to people.
    tpaccept:
        description: Accept a players request to teleport.
    tpahere:
        description: Request a player to teleport to you.
    tpallhere:
        description: Tp all players to you.
    tpback:
        description: Teleport back to your previous location.
    tphere:
        description: Teleport a player to you.
    tpo:
        description: Teleport to a player overriding their teleportation option.
    tpohere:
        description: Teleport a player to you overriding their teleportation option.
    tpreject:
        description: Reject someones requests to teleport to you.
    tpsilent:
        description: Teleport to a player with out it telling them.
    tptoggle:
        description: Toggle the ability for player to tp to you.
